### PR TITLE
add the *actually pretty cool* react-a-likes

### PR DESCRIPTION
**Pull request by alexwilson**
so like,, if you could merge this pr, that'd be great

_(wasn't sure if inferno is best stylised as inferno or infernojs but this seems fine)_

### CODE REVIEW

**Comment by walaura** [comment]
i think these might be too obscure? can we just do `infernojs`? its also obscure, i only know it from @guardian but it has js in the name so it makes for funnies

**Comment by alexwilson** [comment]
sure, happy to make that change — raxjs (alibaba) and nervjs (jd.com) might be good additions too as they're rather big in china, ok to keep them?

**Comment by alexwilson** [comment]
(tbh these should all have been stylised as <X>js.)

**Comment by walaura** [comment]
bring 'em!!!

i was thinking, (we should do this for all of them) i wanna drop links in a comment below for ever library too

**Comment by alexwilson** [comment]
done !

**Review by walaura — APPROVED** [review]

**Pull request merged**
